#
# This is free software, lisence use MIT.
# 22
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
# 111j

name: Merge-upstream

on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 19 * * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config --global user.email "yjw8886@gmail.com"
          git config --global user.name "yjw8886"

      - name: ignore yml file
        run: git update-index --assume-unchanged .github/workflows/

      - name: Load upstream commits
        run: git pull https://github.com/coolsnowwolf/lede.git --no-edit --strategy-option ours

      - name: merge hello world
        run: |
          git clone https://github.com/fw876/helloworld.git
          rm -rf package/lean/luci-app-ssr-plus
          mv helloworld/luci-app-ssr-plus package/lean/
          rm -rf helloworld
          git add -A
          git commit -m "add hello world"

      #        run: rm -rf /lede/.github/workflows/ci.yml


      - name: Push Commits
        env:
          DOWNSTREAM_BRANCH: master
        run: git push origin $DOWNSTREAM_BRANCH
