#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: x64basic

on:
  push:
    branches: 
      - master
  #     ↑↑↑ 改成你的分支名, 一般是master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
        #      ↑↑↑ 改成你的分支名, 一般是master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # ========================固件定制部分========================
          # 
          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 
          # 以下为定制化固件选项和说明:
          #
          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #
          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 
          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          # CONFIG_AMULE_CRYPTOPP_STATIC_LINKING is not set
          # CONFIG_BUSYBOX_DEFAULT_FEATURE_IPV6 is not set
          # CONFIG_DRIVER_11AC_SUPPORT is not set
          # CONFIG_DRIVER_11N_SUPPORT is not set
          # CONFIG_DRIVER_11W_SUPPORT is not set
          # CONFIG_GRUB_CONSOLE is not set
          # CONFIG_IPV6 is not set
          # CONFIG_KERNEL_AIO is not set
          # CONFIG_KERNEL_CGROUP_CPUACCT is not set
          # CONFIG_KERNEL_CGROUP_SCHED is not set
          # CONFIG_KERNEL_CPUSETS is not set
          # CONFIG_KERNEL_FANOTIFY is not set
          # CONFIG_KERNEL_FHANDLE is not set
          # CONFIG_KERNEL_IPV6 is not set
          # CONFIG_KERNEL_MEMCG is not set
          # CONFIG_KERNEL_RESOURCE_COUNTERS is not set
          # CONFIG_LUCI_SRCDIET is not set
          # CONFIG_OPENSSL_OPTIMIZE_SPEED is not set
          # CONFIG_PACKAGE_UnblockNeteaseMusic is not set
          # CONFIG_PACKAGE_adbyby is not set
          # CONFIG_PACKAGE_alsa-lib is not set
          # CONFIG_PACKAGE_alsa-utils is not set
          # CONFIG_PACKAGE_ath10k-firmware-qca9888 is not set
          # CONFIG_PACKAGE_ath10k-firmware-qca988x is not set
          # CONFIG_PACKAGE_ath10k-firmware-qca9984 is not set
          # CONFIG_PACKAGE_ath9k-htc-firmware is not set
          CONFIG_PACKAGE_attr=y
          # CONFIG_PACKAGE_automount is not set
          # CONFIG_PACKAGE_autosamba is not set
          # CONFIG_PACKAGE_bnx2-firmware is not set
          # CONFIG_PACKAGE_brcmfmac-firmware-43602a1-pcie is not set
          # CONFIG_PACKAGE_coremark is not set
          CONFIG_PACKAGE_dbus=y
          # CONFIG_PACKAGE_ddns-scripts is not set
          # CONFIG_PACKAGE_ddns-scripts_aliyun is not set
          # CONFIG_PACKAGE_etherwake is not set
          # CONFIG_PACKAGE_hostapd-common is not set
          # CONFIG_PACKAGE_htop is not set
          # CONFIG_PACKAGE_iptables-mod-conntrack-extra is not set
          # CONFIG_PACKAGE_iptables-mod-ipopt is not set
          # CONFIG_PACKAGE_iptables-mod-ipsec is not set
          # CONFIG_PACKAGE_iw is not set
          # CONFIG_PACKAGE_iwinfo is not set
          # CONFIG_PACKAGE_kmod-ac97 is not set
          # CONFIG_PACKAGE_kmod-ath is not set
          # CONFIG_PACKAGE_kmod-ath10k is not set
          # CONFIG_PACKAGE_kmod-ath5k is not set
          # CONFIG_PACKAGE_kmod-ath9k is not set
          # CONFIG_PACKAGE_kmod-ath9k-htc is not set
          # CONFIG_PACKAGE_kmod-bnx2 is not set
          # CONFIG_PACKAGE_kmod-bonding is not set
          # CONFIG_PACKAGE_kmod-button-hotplug is not set
          # CONFIG_PACKAGE_kmod-cfg80211 is not set
          # CONFIG_PACKAGE_kmod-crypto-aead is not set
          # CONFIG_PACKAGE_kmod-crypto-arc4 is not set
          # CONFIG_PACKAGE_kmod-crypto-authenc is not set
          # CONFIG_PACKAGE_kmod-crypto-cbc is not set
          # CONFIG_PACKAGE_kmod-crypto-deflate is not set
          # CONFIG_PACKAGE_kmod-crypto-des is not set
          # CONFIG_PACKAGE_kmod-crypto-ecb is not set
          # CONFIG_PACKAGE_kmod-crypto-echainiv is not set
          # CONFIG_PACKAGE_kmod-crypto-gf128 is not set
          # CONFIG_PACKAGE_kmod-crypto-hmac is not set
          # CONFIG_PACKAGE_kmod-crypto-manager is not set
          # CONFIG_PACKAGE_kmod-crypto-md5 is not set
          # CONFIG_PACKAGE_kmod-crypto-misc is not set
          # CONFIG_PACKAGE_kmod-crypto-null is not set
          # CONFIG_PACKAGE_kmod-crypto-pcompress is not set
          # CONFIG_PACKAGE_kmod-crypto-rng is not set
          # CONFIG_PACKAGE_kmod-crypto-sha1 is not set
          # CONFIG_PACKAGE_kmod-crypto-sha256 is not set
          # CONFIG_PACKAGE_kmod-crypto-wq is not set
          # CONFIG_PACKAGE_kmod-crypto-xts is not set
          # CONFIG_PACKAGE_kmod-gre is not set
          # CONFIG_PACKAGE_kmod-i40e is not set
          # CONFIG_PACKAGE_kmod-i40evf is not set
          # CONFIG_PACKAGE_kmod-ifb is not set
          # CONFIG_PACKAGE_kmod-igb is not set
          # CONFIG_PACKAGE_kmod-igbvf is not set
          # CONFIG_PACKAGE_kmod-ipsec is not set
          # CONFIG_PACKAGE_kmod-ipt-conntrack-extra is not set
          # CONFIG_PACKAGE_kmod-ipt-ipopt is not set
          # CONFIG_PACKAGE_kmod-ipt-ipsec is not set
          # CONFIG_PACKAGE_kmod-ixgbe is not set
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          # CONFIG_PACKAGE_kmod-mac80211 is not set
          # CONFIG_PACKAGE_kmod-mppe is not set
          # CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set
          # CONFIG_PACKAGE_kmod-nf-ipt6 is not set
          # CONFIG_PACKAGE_kmod-pcnet32 is not set
          # CONFIG_PACKAGE_kmod-rt2800-usb is not set
          # CONFIG_PACKAGE_kmod-rt2x00-lib is not set
          # CONFIG_PACKAGE_kmod-sched-cake is not set
          # CONFIG_PACKAGE_kmod-sched-core is not set
          # CONFIG_PACKAGE_kmod-sound-hda-core is not set
          # CONFIG_PACKAGE_kmod-sound-mpu401 is not set
          # CONFIG_PACKAGE_kmod-sound-via82xx is not set
          # CONFIG_PACKAGE_kmod-tulip is not set
          # CONFIG_PACKAGE_kmod-tun is not set
          # CONFIG_PACKAGE_kmod-usb-audio is not set
          # CONFIG_PACKAGE_kmod-usb-net is not set
          # CONFIG_PACKAGE_kmod-vmxnet3 is not set
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libavahi-dbus-support=y
          # CONFIG_PACKAGE_libcurl is not set
          CONFIG_PACKAGE_libdaemon=y
          CONFIG_PACKAGE_libdbus=y
          # CONFIG_PACKAGE_libevent2 is not set
          CONFIG_PACKAGE_libexpat=y
          # CONFIG_PACKAGE_libgmp is not set
          # CONFIG_PACKAGE_libip6tc is not set
          # CONFIG_PACKAGE_libminiupnpc is not set
          # CONFIG_PACKAGE_libnatpmp is not set
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          # CONFIG_PACKAGE_luci-app-arpbind is not set
          # CONFIG_PACKAGE_luci-app-autoreboot is not set
          # CONFIG_PACKAGE_luci-app-ddns is not set
          # CONFIG_PACKAGE_luci-app-filetransfer is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          # CONFIG_PACKAGE_luci-app-pptp-server is not set
          # CONFIG_PACKAGE_luci-app-samba is not set
          # CONFIG_PACKAGE_luci-app-sqm is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server is not set
          # CONFIG_PACKAGE_luci-app-transmission is not set
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          # CONFIG_PACKAGE_luci-app-upnp is not set
          # CONFIG_PACKAGE_luci-app-v2ray-server is not set
          # CONFIG_PACKAGE_luci-app-vlmcsd is not set
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_luci-app-wol is not set
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          # CONFIG_PACKAGE_luci-proto-bonding is not set
          # CONFIG_PACKAGE_nlbwmon is not set
          # CONFIG_PACKAGE_node is not set
          CONFIG_PACKAGE_openssh-sftp-server=y
          # CONFIG_PACKAGE_openssl-util is not set
          CONFIG_PACKAGE_perl=y
          CONFIG_PACKAGE_perlbase-base=y
          CONFIG_PACKAGE_perlbase-bytes=y
          CONFIG_PACKAGE_perlbase-class=y
          CONFIG_PACKAGE_perlbase-config=y
          CONFIG_PACKAGE_perlbase-cwd=y
          CONFIG_PACKAGE_perlbase-errno=y
          CONFIG_PACKAGE_perlbase-essential=y
          CONFIG_PACKAGE_perlbase-fcntl=y
          CONFIG_PACKAGE_perlbase-file=y
          CONFIG_PACKAGE_perlbase-filehandle=y
          CONFIG_PACKAGE_perlbase-i18n=y
          CONFIG_PACKAGE_perlbase-integer=y
          CONFIG_PACKAGE_perlbase-io=y
          CONFIG_PACKAGE_perlbase-list=y
          CONFIG_PACKAGE_perlbase-locale=y
          CONFIG_PACKAGE_perlbase-params=y
          CONFIG_PACKAGE_perlbase-posix=y
          CONFIG_PACKAGE_perlbase-re=y
          CONFIG_PACKAGE_perlbase-scalar=y
          CONFIG_PACKAGE_perlbase-selectsaver=y
          CONFIG_PACKAGE_perlbase-socket=y
          CONFIG_PACKAGE_perlbase-symbol=y
          CONFIG_PACKAGE_perlbase-tie=y
          CONFIG_PACKAGE_perlbase-unicore=y
          CONFIG_PACKAGE_perlbase-utf8=y
          CONFIG_PACKAGE_perlbase-xsloader=y
          # CONFIG_PACKAGE_pptpd is not set
          # CONFIG_PACKAGE_proto-bonding is not set
          # CONFIG_PACKAGE_rt2800-usb-firmware is not set
          # CONFIG_PACKAGE_samba36-server is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-server is not set
          # CONFIG_PACKAGE_sqm-scripts is not set
          # CONFIG_PACKAGE_strongswan is not set
          # CONFIG_PACKAGE_strongswan-charon is not set
          # CONFIG_PACKAGE_strongswan-ipsec is not set
          # CONFIG_PACKAGE_strongswan-minimal is not set
          # CONFIG_PACKAGE_strongswan-mod-aes is not set
          # CONFIG_PACKAGE_strongswan-mod-gmp is not set
          # CONFIG_PACKAGE_strongswan-mod-hmac is not set
          # CONFIG_PACKAGE_strongswan-mod-kernel-netlink is not set
          # CONFIG_PACKAGE_strongswan-mod-nonce is not set
          # CONFIG_PACKAGE_strongswan-mod-pubkey is not set
          # CONFIG_PACKAGE_strongswan-mod-random is not set
          # CONFIG_PACKAGE_strongswan-mod-sha1 is not set
          # CONFIG_PACKAGE_strongswan-mod-socket-default is not set
          # CONFIG_PACKAGE_strongswan-mod-stroke is not set
          # CONFIG_PACKAGE_strongswan-mod-updown is not set
          # CONFIG_PACKAGE_strongswan-mod-x509 is not set
          # CONFIG_PACKAGE_strongswan-mod-xauth-generic is not set
          # CONFIG_PACKAGE_strongswan-mod-xcbc is not set
          # CONFIG_PACKAGE_tc is not set
          # CONFIG_PACKAGE_transmission-daemon-openssl is not set
          # CONFIG_PACKAGE_transmission-web-control is not set
          # CONFIG_PACKAGE_vlmcsd is not set
          # CONFIG_PACKAGE_vsftpd-alt is not set
          # CONFIG_PACKAGE_wireless-regdb is not set
          # CONFIG_PACKAGE_wpad is not set
          # CONFIG_PACKAGE_zerotier is not set
          CONFIG_PERL_NOCOMMENT=y
          CONFIG_PERL_THREADS=y
          # CONFIG_VMDK_IMAGES is not set
          # CONFIG_PACKAGE_NTFS-3G_USE_LIBFUSE is not set
          # CONFIG_PACKAGE_beep is not set
          CONFIG_PACKAGE_ca-bundle=y
          CONFIG_PACKAGE_coreutils-nohup=y
          # CONFIG_PACKAGE_kmod-ac97 is not set
          CONFIG_PACKAGE_kmod-fs-exfat=y
          CONFIG_PACKAGE_kmod-fs-ext4=y
          CONFIG_PACKAGE_kmod-fs-vfat=y
          CONFIG_PACKAGE_kmod-fuse=y
          # CONFIG_PACKAGE_kmod-hwmon-adcxx is not set
          # CONFIG_PACKAGE_kmod-hwmon-ads1015 is not set
          # CONFIG_PACKAGE_kmod-hwmon-adt7410 is not set
          # CONFIG_PACKAGE_kmod-hwmon-adt7475 is not set
          CONFIG_PACKAGE_kmod-hwmon-core=y
          # CONFIG_PACKAGE_kmod-hwmon-gpiofan is not set
          # CONFIG_PACKAGE_kmod-hwmon-ina209 is not set
          # CONFIG_PACKAGE_kmod-hwmon-ina2xx is not set
          # CONFIG_PACKAGE_kmod-hwmon-it87 is not set
          # CONFIG_PACKAGE_kmod-hwmon-lm63 is not set
          # CONFIG_PACKAGE_kmod-hwmon-lm75 is not set
          # CONFIG_PACKAGE_kmod-hwmon-lm77 is not set
          # CONFIG_PACKAGE_kmod-hwmon-lm85 is not set
          # CONFIG_PACKAGE_kmod-hwmon-lm90 is not set
          # CONFIG_PACKAGE_kmod-hwmon-lm92 is not set
          # CONFIG_PACKAGE_kmod-hwmon-lm95241 is not set
          # CONFIG_PACKAGE_kmod-hwmon-ltc4151 is not set
          # CONFIG_PACKAGE_kmod-hwmon-nct6775 is not set
          # CONFIG_PACKAGE_kmod-hwmon-pc87360 is not set
          # CONFIG_PACKAGE_kmod-hwmon-pwmfan is not set
          # CONFIG_PACKAGE_kmod-hwmon-sch5627 is not set
          # CONFIG_PACKAGE_kmod-hwmon-sht21 is not set
          # CONFIG_PACKAGE_kmod-hwmon-tmp102 is not set
          # CONFIG_PACKAGE_kmod-hwmon-tmp103 is not set
          # CONFIG_PACKAGE_kmod-hwmon-tmp421 is not set
          # CONFIG_PACKAGE_kmod-hwmon-vid is not set
          # CONFIG_PACKAGE_kmod-hwmon-w83627ehf is not set
          # CONFIG_PACKAGE_kmod-hwmon-w83627hf is not set
          # CONFIG_PACKAGE_kmod-hwmon-w83793 is not set
          CONFIG_PACKAGE_kmod-i2c-algo-bit=y
          # CONFIG_PACKAGE_kmod-i2c-algo-pca is not set
          # CONFIG_PACKAGE_kmod-i2c-algo-pcf is not set
          CONFIG_PACKAGE_kmod-i2c-core=y
          # CONFIG_PACKAGE_kmod-i2c-gpio is not set
          # CONFIG_PACKAGE_kmod-i2c-i801 is not set
          # CONFIG_PACKAGE_kmod-i2c-mux is not set
          # CONFIG_PACKAGE_kmod-i2c-piix4 is not set
          # CONFIG_PACKAGE_kmod-i2c-pxa is not set
          # CONFIG_PACKAGE_kmod-i2c-smbus is not set
          # CONFIG_PACKAGE_kmod-i2c-tiny-usb is not set
          CONFIG_PACKAGE_kmod-lib-crc16=y
          CONFIG_PACKAGE_kmod-nls-cp437=y
          CONFIG_PACKAGE_kmod-nls-iso8859-1=y
          CONFIG_PACKAGE_kmod-nls-utf8=y
          # CONFIG_PACKAGE_kmod-pcspkr is not set
          # CONFIG_PACKAGE_kmod-pmbus-core is not set
          # CONFIG_PACKAGE_kmod-pmbus-zl6100 is not set
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-sound-core=y
          # CONFIG_PACKAGE_kmod-sound-dummy is not set
          # CONFIG_PACKAGE_kmod-sound-ens1371 is not set
          # CONFIG_PACKAGE_kmod-sound-hda-core is not set
          # CONFIG_PACKAGE_kmod-sound-i8x0 is not set
          # CONFIG_PACKAGE_kmod-sound-mpu401 is not set
          # CONFIG_PACKAGE_kmod-sound-seq is not set
          # CONFIG_PACKAGE_kmod-sound-soc-ac97 is not set
          # CONFIG_PACKAGE_kmod-sound-soc-core is not set
          # CONFIG_PACKAGE_kmod-sound-via82xx is not set
          # CONFIG_PACKAGE_kmod-usb-audio is not set
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-storage-extras=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_luci-lib-fs=y
          CONFIG_PACKAGE_miniupnpd=y
          CONFIG_PACKAGE_ntfs-3g=y
          EOF
          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_PAD is not set
          # CONFIG_VMDK_IMAGES is not set
          EOF
          # 
          # ========================固件定制部分结束========================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: bin/targets
